# config.yaml
data_path: "./data/daily_sentiment.csv"          # path to training CSV, empty uses synthetic data
eval_data_path: ""     # path for evaluation
universe_size: 5
features_dim: 5
max_gross_leverage: 2.0
per_asset_max: 1.0
transaction_cost: 0.001
slippage_coeff: 0.001
margin_interest: 0.0005
start_cash: 1.0

# RL training params
learning_rate: 0.0003
gamma: 0.99
entropy_coef: 0.01
batch_size: 64
tensorboard_log: "./logs/"
output_model_path: "./models/ppo_sentiment"
output_env_norm: ".models/env_norm.pkl"
equity_curve_path: "./logs/"


